# config file version
apiVersion: 1

# datasources: list of datasources to be created/configured
datasources:
  # datasource object
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: test
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
